name: Build override
on:
  workflow_dispatch:
  schedule:
    - cron: "30 21 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v3.1.1
        
      - name: install yaml
        run: |
          pip install ruamel.yaml
                    
      - name: Checkout codebase
        uses: actions/checkout@v3
        
      - name: rm *.stoverride
        run: |
          rm -rf ./*.stoverride
          ls -l
          
      - name: Run Python
        run: |
          python3 convert.py
          
      - name: Check if there is any new translations
        id: verify_diff
        run: |
          git diff --quiet * || echo "::set-output name=new_translations_exist::true"
          
      - name: Get current date
        id: date
        if: steps.verify_diff.outputs.new_translations_exist == 'true'
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"
          
      - name: Git commit
        if: steps.verify_diff.outputs.new_translations_exist == 'true'
        run: |
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "${{ steps.date.outputs.today }}"
      
      - name: Push changes
        if: steps.verify_diff.outputs.new_translations_exist == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
